import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import StyledComponentsRegistry from '@/lib/styled-components/registry'
import { Theme } from '@/providers/Theme'
import type { Metadata } from 'next'
import { Poppins, Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Kodi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body className={`${roboto.variable} ${poppins.variable}`}>
        <StyledComponentsRegistry>
          <Theme>
            <Header />
            {children}
            <Footer />
          </Theme>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
